added do-not-disturb.md
DVELP/cookbook pull request #129
Opened 2019-04-04 12:03 UTC by andreas-kater

2019-04-04 20:28 UTC, tom-mullen requested changes

2019-04-04 20:28 UTC, tom-mullen commented on handbook/README.md
> +  * [Do-Not-Disturb Mode](best-practice/anti-harassment.md)
Feels like this one should be in the quick reference guide?

2019-04-04 20:28 UTC, tom-mullen commented on handbook/README.md
> +  * [Anti-Harassment and Bullying Policy](best-practice/anti-harassment.md)
These look like they belong in a different PR?

2019-04-04 20:28 UTC, tom-mullen commented on handbook/best-practice/do-not-disturb.md
> +attention, we ask for a notification to be sent anyway. Otherwise we make a note
I personally use `/remind me to message this person in 1 hour` functionality in slack as a reminder.

2019-04-10 16:01 UTC, annisem approved these changes
Looks good

2019-04-10 16:17 UTC, merged