Add Harvest Forecast Guide to DVELP Cookbook
DVELP/cookbook pull request #26
Opened 2016-08-08 10:20 UTC by latimerjason

Add Harvest Forecast guide and update read me with link

DVELP uses Forecast to plan our time and estimate availability before
taking on new work. Share the process of how DVELP plans resources in
our GitHub cookbook

2016-08-08 10:43 UTC, latimerjason commented on guides/harvest-forecast.md
> +New requests and changes are planned into Forecast daily. Any changes to the current week are reviewed with the impacted teams in real time.
New client requests and changes are planned into Forecast daily.

2016-09-15 13:07 UTC, tom-mullen commented on guides/harvest-forecast.md
> +Full projects are estimated and planned in their entierty. Small improvement works (<2 days) are planned in detail across the next two weeks.
@latimerjason typo 'entirety'

2016-09-15 13:09 UTC, tom-mullen requested changes
Just one typo

2016-09-28 11:51 UTC, latimerjason commented
@tom-mullen - change has been made. Can we ship?

2016-10-03 23:41 UTC, tom-mullen approved these changes

2016-10-04 09:56 UTC, merged