Create logging guide
DVELP/cookbook pull request #38
Opened 2018-02-08 14:28 UTC by vitaliiprodan

Why:

* Create the doc where other developers could see our logging standards

2018-02-08 19:05 UTC, tom-mullen requested changes

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +In this doc we are going to introduce you to our application diagnostics and logging style and approach.
@vitaliiprodan I think we should try on focus on the 'why' in introductory paragraphs:

> Shipping apps to a production environment is paramount in our development cycle. Having the correct tools in place to monitor and diagnose issues is essential.

> The following is the baseline setup for logging and error tracking in Rails applications at DVELP.

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +## The Challenge
I see what you are doing here, but developers tend not to care about the challenge (developers are our audience here), so let's get to the code. Recommend removing this paragraph.

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +## The Solution
Change to 

## Logging

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +
### Papertail

For consistency and consolidation, we use a corporate [Papertrail](https://papertrailapp.com) account for logging purposes.

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +[lograge](https://github.com/roidrage/lograge) is a gem which helps us with application logging configuration. You can find the recommended gem configuration below:
### Lograge
To prevent overly verbose logs, we recommend using [lograge](https://github.com/roidrage/lograge) to filter out the noise and provide more clarity.

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +### Application configuration
Remove this line

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +Creating a new papertrail system for Heroku applications - [https://papertrailapp.com/systems/setup?type=app&platform=heroku]()
Move this under Papertrail above and put in under the the title `Setup`

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +# Error reporting API
## Error Handling

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +As with the [papertrail](https://papertrailapp.com) corporate account we have [Sentry](https://sentry.io) account. The installation guide you can find by [this link](https://github.com/getsentry/rave
I think you should put the Sentry installation and config in this doc. The idea is to make it easy for people to reference without having to head off to different pages.

Depending on where you look, you will get different instructions and the aim of this document is to insure consistency of approach across all codebases.

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +# Naming
*This part should go at the top of the document*, if they get here they have probably already set up the projects, now they have to go and change the names :-)

## Naming Conventions

2018-02-08 19:05 UTC, tom-mullen commented on guides/Diagnostics.md
> +Make sure you have the same names for Heroku application, sentry project and papertrail system. It's very important to keep all things with correct naming.
Can you add an example?

`e.g. dvelp-production`

2018-02-08 19:07 UTC, tom-mullen requested changes

2018-02-08 19:07 UTC, tom-mullen commented on guides/Diagnostics.md
> +# Diagnostics
You have created this page, but not added a link to it from the menu. I would also recommend going with lowercase for the filename.

2018-02-12 10:25 UTC, vitaliiprodan commented
@tom-mullen fixed

2018-02-28 17:52 UTC, tom-mullen approved these changes

2018-03-01 08:09 UTC, merged