Add How we approach 'questions' to Mentoring
DVELP/cookbook pull request #49
Opened 2018-10-04 12:45 UTC by vitaliiprodan

Why:

* Explain people fundamental principles of asking the questions in DVELP

2018-10-08 15:20 UTC, tom-mullen requested changes

2018-10-08 15:20 UTC, tom-mullen commented on handbook/mentoring.md
> +### How we approach 'questions'
### Make Questions Multiple Choice

Asking questions is a fundamental part to learning. We have a nifty trick to get to your answer more quickly: make the question multiple choice.

By sending proposals along with your question, you will help the recipient to:

- Get up-to-speed with the context
- Show you have done research and are really stuck
- Allow them to choose, augment or add to the proposed solutions

A 'warm-up' question of 'hey, I'm working on this problem, have we solved it before?' is  always good place to start.

So remember, make sure the next time you ask a question, send some proposals too.

2018-10-12 16:04 UTC, vitaliiprodan commented on handbook/mentoring.md
> +### How we approach 'questions'
@tom-mullen fixed

2018-10-12 16:05 UTC, vitaliiprodan commented
@tom-mullen fixed

2018-10-14 20:01 UTC, tom-mullen approved these changes

2018-10-16 15:40 UTC, merged